[package]
name = "stable-hash"
version = "0.4.0"
authors = ["Zac Burns <That3Percent@gmail.com>"]
edition = "2018"

[profile.release]
debug = true


[features]
simd = ["packed_simd"]


[dependencies]
blake3 = "0.3.3"
num-traits = "0.2.11"
leb128 = "0.2.4"
ibig = "0.3.1"
packed_simd = { version = "0.3.6", package = "packed_simd_2", optional = true }
lazy_static = "1.4.0"
firestorm = "0.4.6"


[dev-dependencies]
twox-hash = "1.5.0"
hex = "0.4.2"
rand = { version = "0.8.4", features = ["small_rng"] }
criterion = "0.3"


[[bench]]
name = "fld_mixer"
harness = false
